project:
  type: website

website:
  title: "Jody Park"
  description: "Jody Park is a first-year PhD student in Political Science/Social Data Analytics at Penn State."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

